### ISSUE TITLE
ability to add feed for students' moodle blogs

### ISSUE THREAD

**Issue by ghost** [djplaner/moodle-mod_bim#13]
for a variety of reasons, not all students are comfortable with using external blogging services for their learning.  why not give them the ability to add feeds for their Moodle blogs?

**Comment by djplaner** [comment]
BIM is designed to work with feeds (RSS/ATOM and similar).  Students can use anything that generates such a feed.  

So, if a Moodle blog can generate a feed, they should be able to register.

I haven't played with the Moodle blog, so not sure if and how it generates a feed.

If this doesn't work, I'll have to admit that I'm not keen to add something special to BIM to support the Moodle blogs.  But could be talked into it.  Will think more about this.  Should probably explore this and offer some directions.

Thanks for reminding me about this Alan.

**Comment by djplaner** [comment]
Have looked into this and, for the time being, won't be doing anything about this.

Some explanation here http://davidtjones.wordpress.com/2010/05/02/can-bim-support-the-use-of-moodle-blogs/

Basically, a student's Moodle blog turns out not to be all that more closed than a Wordpress.com blog.  Especially if the Wordpress.com blog is kept anonymous.

THere's also the general flakiness and poor utility of the Moodle blog.  Moving to Moodle 2.0 might change this.
